prod:
  image: vizzuality/converter:1.4.5${STAGING}
  ports:
    - "4100:4100"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: converter${STAGING}
