version: "3"
services:
  develop:
    build: .
    ports:
      - "4100:4100"
    container_name: converter-develop
    environment:
      NODE_ENV: dev
      NODE_PATH: ./app/src
      PORT: 4100
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/converter/app
