version: "3"
services:
  develop:
    build: .
    container_name: converter-develop
    environment:
      NODE_ENV: dev
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: develop
    volumes:
      - ./app:/opt/converter/app

